# Generated by Django 4.2.15 on 2024-09-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('price', models.FloatField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
